### ISSUE TITLE
New MEV relays for consideration and potential inclusion

### ISSUE THREAD

**Issue by randomishwalk** [eth-educators/ethstaker-guides#60]
Two new relays have emerged: [11/30/22 Twitter announcement](https://twitter.com/ultrasoundmoney/status/1597939734088908800?s=20&t=2-BGshHvp2FNKcuzigKaKw)
- [Ultrasound Money relay](https://relay.ultrasound.money/)
- [Gnosis agnostic relay](https://agnostic-relay.net/)

_[Reference: existing relay list](https://github.com/eth-educators/ethstaker-guides/blob/main/MEV-relay-list.md)_

**Comment by remyroy** [comment]
Initial details were added with c85ccb3afbe6640b70bad40115a22dfcce7fc115 . We'll try to gather the remaining info.

**Comment by randomishwalk** [comment]
Awesome thanks for being proactive & fast on this!

**Comment by randomishwalk** [comment]
Ok to close this? Or are you still gathering details on the two new relays? Relay list seems pretty filled out from what I can tell for the Gnosis and ultrasoundmoney entries

**Comment by remyroy** [comment]
They were added. I haven't been able to get more details so far so I guess we can close this.
