### ISSUE TITLE
need some geth for dapps

### ISSUE THREAD

**Issue by BetDEXben** [eth-educators/ethstaker-guides#74]
can anyone here help give 320 Göerli? i've spent about $200 on goerli because the faucet doesn't give enough maybe here someone can help me thanks.

**Comment by remyroy** [comment]
You don't need Goerli for dapps. Simply use Sepolia, Hardhat or Gnosis chain which are all good alternatives.

**Comment by BetDEXben** [comment]
> You don't need Goerli for dapps. Simply use Sepolia, Hardhat or Gnosis chain which are all good alternatives.

can you help send 500 or 1000 sepolia for long term?

**Comment by remyroy** [comment]
You can try various faucets online from https://faucetlink.to/sepolia. They will slowly give you Sepolia ETH. You might not need to get a large amount up front. If you truly need such a large amount up from, there are a few Sepolia operators and large holders you can try to contact.

**Comment by BetDEXben** [comment]
Can you tell me who holds large amounts of sepolia? i need it for a long time

**Comment by mcdee** [comment]
@BetDEXben sent you 500 sepolia ETH.

**Comment by BetDEXben** [comment]
> @BetDEXben sent you 500 sepolia ETH.

thank you very much appreciate!

**Comment by yagolgmesol** [comment]
@mcdee can you send me to 1000-2000 sepolia or do i have to buy it? i need to spread to dapss developers who are moving from goerli to sepolia for further testing
